[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x railway_migrate.sh"]

[start]
cmd = "bash railway_migrate.sh && uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
