# Let Nixpacks auto-detect Python from runtime.txt
[phases.setup]
nixPkgs = ["postgresql"]

[phases.install]

[phases.build]
cmds = ["chmod +x railway_migrate.sh"]

[start]
cmd = "bash railway_migrate.sh && uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
