[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["python3.10 -m pip install --upgrade pip", "python3.10 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x railway_migrate.sh"]

[start]
cmd = "bash railway_migrate.sh && python3.10 -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
